# Generated by Django 2.2.20 on 2021-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Date(mm/dd/2021)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
