# Generated by Django 2.2.20 on 2021-05-14 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210514_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='good',
            field=models.CharField(choices=[('A1', 'Уход за ногтями'), ('A2', 'Легкий маникюр'), ('A3', 'Педикюр'), ('A4', 'Наращивание'), ('A5', 'Уходы'), ('A6', 'Педикюр + '), ('A7', 'Маникюр + гель лак')], max_length=2, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.CharField(choices=[('B1', 'Алина Биккинина'), ('B2', 'Марина Касаткина'), ('B3', 'Екатерина Колесникова'), ('B4', 'Альфина Юнусова'), ('B5', 'Аделина Илькаева'), ('B6', 'Ильвира Зорина'), ('B7', 'Анна Баникова'), ('B8', 'Валерия Хайруллина')], max_length=2, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='(дата/месяй/год)'),
            preserve_default=False,
        ),
    ]
